name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: true

  lint:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint
        env:
          CI: true

  unit_tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test:unit
        env:
          CI: true

  integration_tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Integration Tests
        run: npm run test:integration
        env:
          CI: true

  e2e_tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run E2E Tests
        run: npm run test:e2e
        env:
          CI: true
